name: Code Style
on:
  push:
    paths:
      - 'Server/**.go'
permissions:
  contents: read

jobs:
  golangci:
    name: Lint Go
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: Server
          skip-go-installation: true
          args: -E bodyclose -E dupl -E exhaustive -E funlen -E godox -E unparam -E wastedassign -E gosec -E goconst
